#!/bin/sh

# source $HOME/.profile

xrdb $HOME/.Xresources &

export OOO_FORCE_DESKTOP=GNOME
export XMODIFIERS="@im=yong"
export GTK_IM_MODULE=yong
export QT_IM_MODULE=yong

xset s off
xset -dpms
# 禁用beep声音
xset -b
