#!/bin/sh

# source $HOME/.profile

xrdb $HOME/.Xresources &

export OOO_FORCE_DESKTOP=GNOME
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

xset s off
xset -dpms
# 禁用beep声音
xset -b
